# Generated by Django 3.2 on 2022-12-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=512)),
                ('Matricule', models.CharField(max_length=512)),
                ('Adresse', models.CharField(max_length=2048)),
                ('Date', models.DateField()),
                ('Heur', models.CharField(max_length=512)),
                ('Nb_heur', models.IntegerField()),
                ('Prix', models.FloatField(blank=True)),
            ],
        ),
    ]
