# Generated by Django 3.2 on 2022-12-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Heur',
            new_name='Heur_deppart',
        ),
        migrations.AddField(
            model_name='reservation',
            name='Heur_arriver',
            field=models.CharField(default='', max_length=512),
        ),
    ]
